version: '3'
networks:
  default:
    external:
      name: my_network
services:
  llm_server_sum:
    image: bogdal1993/llm_server
    networks:
      - default
    restart: always 
    ports:
      - "8005:8005"
    volumes:
      - ./mistral7b_dialsum_Q6_K.gguf:/mistral7b_dialsum_Q6_K.gguf
    command: uvicorn main:app --port 8005 --host 0.0.0.0