version: '3'
networks:
  default:
    external:
      name: my_network
services:
  nginx:
    image: "nginx:stable"
    volumes:
      - ./web:/mnt/vp/web
    networks:
      - default
    container_name: nginx
    ports:
      - "80:80"
  file_api:
    image: bogdal1993/baseweb
    networks:
      - default
    restart: always 
    ports:
      - "8000:8000"
    environment:
        DSN: "postgresql://user:pass@db:5432/tpdb"
        APIURL: "http://127.0.0.1/api/file/"
    volumes:
      - ./file_api/main.py:/opt/file_api/main.py
      - ./media:/opt/media
    working_dir: /opt/file_api/
    command: uvicorn main:app --port 8000 --host 0.0.0.0
  backend_api:
    image: bogdal1993/baseweb
    networks:
      - default
    restart: always 
    ports:
      - "8001:8001"
    environment:
        DSN: "postgresql://user:pass@db:5432/tpdb"
    volumes:
      - ./backend_api/main.py:/opt/backend_api/main.py
      - ./media:/opt/media
    working_dir: /opt/backend_api/
    command: uvicorn main:app --port 8001 --host 0.0.0.0
