services:
  tag_server:
    image: vp/text_processing
    restart: always
    volumes:
      - ./tagserver.py:/opt/tag_server/tagserver.py
      - ./cache:/root
    environment:
        DSN: "postgresql://orangepi:orangepi@192.168.0.172:5432/orangepi"
    working_dir: /opt/tag_server/
    command: python tagserver.py