version: '3.8'

services:
  # vosk:
    # image: alphacep/kaldi-ru:latest
    # restart: always
    # ports:
      # - "2700:2700"
    # volumes:
      # - ./vosk/vosk-model-ru-0.42:/opt/vosk/vosk-model-ru-0.42
      # - ./vosk/vosk-model-spk-0.4:/opt/vosk/vosk-model-spk-0.4
    # env_file:
      # - .env

  transcript:
    image: bogdal1993/base_audio_process_v2
    restart: always
    volumes:
      - ./transcript_server/transcript.py:/opt/transcript_server/transcript.py
      - ./transcript_server/tr_lib.py:/opt/transcript_server/tr_lib.py
      - ./transcript_server/media:/opt/media
      - ./transcript_server/models:/opt/transcript_server/models
      - ./transcript_server/tempmedia:/opt/tempmedia
      - ./transcript_server/models/cache:/root
    env_file:
      - .env
    working_dir: /opt/transcript_server/
    command: python transcript.py
    deploy:
      mode: replicated
      replicas: 1
    # depends_on:
      # - vosk

  text_processor:
    image: bogdal1993/text_processing
    restart: always
    volumes:
      - ./text_processor/textprocessor.py:/opt/text_processor/textprocessor.py
      - ./text_processor/ruword2tags/ruword2tags.db:/root/.ruword2tags/ruword2tags.db
      - ./text_processor/deeppavlov:/root/.deeppavlov
    env_file:
      - .env
    working_dir: /opt/text_processor/
    command: python textprocessor.py
    deploy:
      mode: replicated
      replicas: 1

  tag_server:
    image: bogdal1993/text_processing
    restart: always
    volumes:
      - ./tag_server/tagserver.py:/opt/tag_server/tagserver.py
      - ./tag_server/cache:/root
    env_file:
      - .env
    working_dir: /opt/tag_server/
    command: python tagserver.py
    
  file_api:
    image: bogdal1993/baseweb
    restart: always 
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - ./file_api/main.py:/opt/file_api/main.py
      - ./media:/opt/media
    working_dir: /opt/file_api/
    command: uvicorn main:app --port 8000 --host 0.0.0.0
  backend_api:
    image: bogdal1993/baseweb
    restart: always 
    ports:
      - "8001:8001"
    env_file:
      - .env
    volumes:
      - ./backend_api/main.py:/opt/backend_api/main.py
      - ./media:/opt/media
    working_dir: /opt/backend_api/
    command: uvicorn main:app --port 8001 --host 0.0.0.0
    
  nginx:
    image: nginx:latest
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./web:/mnt/vp/web
    depends_on:
      - file_api
      - backend_api
