version: '2'
services:
  llm_server_sum:
    image: bogdal1993/llm_server
    restart: always 
    ports:
      - "8005:8005"
    volumes:
      - ./summarization_server/mistral7b_dialsum_Q6_K.gguf:/mistral7b_dialsum_Q6_K.gguf
    command: uvicorn main:app --port 8005 --host 0.0.0.0