# Используем базовый образ
FROM bogdal1993/base_audio_process

RUN apt-get update && apt-get install -y ffmpeg
# Устанавливаем необходимые библиотеки
RUN pip install git+https://github.com/wenet-e2e/wespeaker.git

# Клонируем репозиторий GigaAM и устанавливаем его
RUN git clone https://github.com/salute-developers/GigaAM.git /GigaAM
WORKDIR /GigaAM
RUN pip install -e .
RUN pip install PySoundFile
